### ISSUE TITLE
@import should be removed in responsive.less with bootstrap

### ISSUE THREAD

**Issue by etienned** [verekia/initializr#52]
Using the bootstrap version I saw many properties duplicated in the compile CSS file, like this:

``` css
table .span21{
    float:none;
    width:1644px;
    margin-left:0;
    float:none;
    width:1644px;
    margin-left:0;
}
```

After googling a bit I found that:
http://stackoverflow.com/questions/9840474/less-compiler-doubles-everything

And it solves the problem! Basically the import: @import "bootstrap/responsive.less"; is including the files "variables.less" and "mixins.less" again - they are already included in the first import of "bootstrap.less". So, removing these imports in responsive.less fix the problem.
