### ISSUE TITLE
Duplicate Grid CSS Generation

### ISSUE THREAD

**Issue by ghost** [verekia/initializr#61]
Hey Jonathan, what's up!? I just wanted to report a quick issue. It's quite benign, but I thought I'd give you a heads up. If you download a copy of a Initializr Twitter's Bootstrap, compile the less and then check out the resulting CSS, you should see that the CSS rules for the grid are duplicated. For some strange reason, this does not happen with Twitter's own copy of Bootstrap.

It's from the grid.less file, here's the code: `#grid > .core(@gridColumnWidth, @gridGutterWidth);`. It pulls the mixin from mixins.less at line 548. The duplicates are directly after the first rule set. Example:

``` css
    /* Starting at line 150 */
    .row {
        margin-left: -20px;
        *zoom: 1;
    }
    .row:before,
    .row:after {
        display: table;
        content: "";
    }
    .row:after {
        clear: both;
    }
    [class*="span"] {
        float: left;
        margin-left: 20px;
    }
    .container,
    .navbar-fixed-top .container,
    .navbar-fixed-bottom .container {
        width: 940px;
    }
    .span12 {
        width: 940px;
    }
    /* … */
    .span1 {
        width: 60px;
    }

    /* And then it just repeats it again */

    .row {
        margin-left: -20px;
        *zoom: 1;
    }
    .row:before,
    .row:after {
        display: table;
        content: "";
    }
    /* And so on … */
```

The duplicates are a part of the base code and not within media-queries. I've tried to fix it, but can't seem to figure out why it's duplicating the rules. BTW, I'm using CodeKit as the compiler, but I wouldn't think that would cause the issue as the grid output is the only thing that duplicates (from I can see).

Anyway, it's not critical issue, but I thought I would just report the strange behavior. It's been making me crazy as hell just trying to figure out why it's doing it, but I'm no LESS expert. Thanks for all your hard work and great contribution to our community. Cheers!
